name: login

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: 
